- hosts: servers,!nanode,!m81,!edyta.org.pl

  remote_user: root

  gather_facts: false

  tasks:
    - name: sync
      synchronize:
        src: ignore.d.server
        dest: /etc/logcheck
        delete: yes
